spring.datasource:
  url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
  username: sa
  password: ''

spring.jpa:
  show-sql: true
  properties.hibernate:
    dialect: org.hibernate.dialect.H2Dialect
    format_sql: true
